### ISSUE TITLE
Save css-rules added to html-dom from javascript (like addClass() jquery function)

### ISSUE THREAD

**Issue by dimti** [peterbe/mincss#42]
Hello

mincss work awesome. And for full automatic process - me need save css rules, when added from javascript. Example: $elementLI.addClass('active')
1. It possible?
2. How true way for this reason?
3. How i can help with that?

**Comment by peterbe** [comment]
It's sadly poorly documented but yes there is a way.
See https://github.com/peterbe/mincss#ignore-css
